name: Dispatch workflow event
on:
  workflow_dispatch:
jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Post dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ouvroir/website/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
